// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[title].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Blog.tsx";
import * as $$1 from "./islands/DarkMode.tsx";
import * as $$2 from "./islands/Logo.tsx";
import * as $$3 from "./islands/NavBar.tsx";
import * as $$4 from "./islands/NavWrappedPage.tsx";
import * as $$5 from "./islands/Post.tsx";

const manifest = {
  routes: {
    "./routes/[title].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/about.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Blog.tsx": $$0,
    "./islands/DarkMode.tsx": $$1,
    "./islands/Logo.tsx": $$2,
    "./islands/NavBar.tsx": $$3,
    "./islands/NavWrappedPage.tsx": $$4,
    "./islands/Post.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
