// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[title].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/BlogSidebar.tsx";
import * as $$1 from "./islands/CubeProduct.tsx";
import * as $$2 from "./islands/Hero.tsx";
import * as $$3 from "./islands/Logo.tsx";
import * as $$4 from "./islands/NavBar.tsx";
import * as $$5 from "./islands/NavWrappedPage.tsx";
import * as $$6 from "./islands/Post.tsx";
import * as $$7 from "./islands/RandomPost.tsx";

const manifest = {
  routes: {
    "./routes/[title].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/about.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/BlogSidebar.tsx": $$0,
    "./islands/CubeProduct.tsx": $$1,
    "./islands/Hero.tsx": $$2,
    "./islands/Logo.tsx": $$3,
    "./islands/NavBar.tsx": $$4,
    "./islands/NavWrappedPage.tsx": $$5,
    "./islands/Post.tsx": $$6,
    "./islands/RandomPost.tsx": $$7,
  },
  baseUrl: import.meta.url,
};

export default manifest;
